# Source this file from ~/.bashrc

# Open file in already started Emacs running in server mode (M-x server-start).
# Useful to hide Emacs startup cost when editing config files from the shell.
alias edit='emacsclient -n'

# Mostly used for editing GIT commit messages.
# Another option is to set it to "emacsclient" if there is always a graphical
# Emacs running.
export EDITOR="emacs -nw"
